name: Data Quality Check

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas
          pip install great_expectations

      - name: List directory contents (debug)
        run: |
          pwd  # Print the current working directory
          ls -la  # List all files in the current directory

      - name: Change working directory
        run: cd .. && python data_quality_checks.py  # Move up one level to the root directory and run the script
